apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind-ken-view
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
# kubectl create rolebinding rolebind-ken-view --clusterrole=view --namespace=dev --serviceaccount=dev:ken
