apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: prometheus
  name: prometheus
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
# kubectl create ns prometheus
