---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-ro-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

# kubectl create clusterrole role-ro-pods --verb=get,list,watch --resource=pods --namespace=prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-bind-carol-ro-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-ro-pods
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:prometheus
# kubectl create clusterrolebinding carol-ro-pods --clusterrole=role-ro-pods --group=system:serviceaccounts:prometheus
