apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: minio
