apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: aytuar/otus:frontend
    name: frontend
    env:
    - name: PORT
      value: "8000"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "localhost"
    - name: CURRENCY_SERVICE_ADDR
      value: "localhost"
    - name: CART_SERVICE_ADDR
      value: "localhost"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "localhost"
    - name: SHIPPING_SERVICE_ADDR
      value: "localhost"
    - name: CHECKOUT_SERVICE_ADDR
      value: "localhost"
    - name: AD_SERVICE_ADDR
      value: "localhost"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}